const siteSnippets = [
    {
        id: 0,
        technology: "python",
        snippet1: "qe",
        snippet2: "sy",
        snippet3: "",
        snippet4: "",
        snippet5: "",
        snippet6: "",
    },
    {
        id: 1,
        technology: "ws",
        snippet1: "sd",
        snippet2: "",
        snippet3: "",
        snippet4: "",
        snippet5: "",
        snippet6: "",
    },    
    {
        id: 2,
        technology: "test",
        snippet1: "fd",
        snippet2: "",
        snippet3: "",
        snippet4: "",
        snippet5: "",
        snippet6: "",
    },
    {
        id: 3,
        technology: "",
        snippet1: "",
        snippet2: "",
        snippet3: "",
        snippet4: "",
        snippet5: "",
        snippet6: "",
    },
    {
        id: 4,
        technology: "",
        snippet1: "",
        snippet2: "",
        snippet3: "",
        snippet4: "",
        snippet5: "",
        snippet6: "",
    },
    {
        id: 5,
        technology: "",
        snippet1: "",
        snippet2: "",
        snippet3: "",
        snippet4: "",
        snippet5: "",
        snippet6: "",
    }
];

export default siteSnippets;